BATCH_ID = 'BATCH_ID'
PARTITION_COLUMN = 'PARTITION_COLUMN'

# pipelines constants
IN_AMOUNT = 'IN_AMOUNT'
OUT_AMOUNT = 'OUT_AMOUNT'
OUT_TABLE = 'OUT_TABLE'

HASH_SUM_MANAGER = 'HASH_SUM_MANAGER'

DEFAULT_DATETIME_PATTERN = '%Y-%m-%d %H:%M:%S'

# available datasource constants
GENERIC_REST_DATASOURCE = 'GENERIC-REST'
EXPECTED_HOURS_DATASOURCE = 'EXP-HOURS-REST'
SMART_RECRUITERS_DATASOURCE = 'SMART-RECRUITERS-REST'
ACCUMULATIVE_DATASOURCE = 'ACCUMULATIVE'

# available granularity
MINUTES = 'minutes'
SECONDS = 'seconds'
HOURS = 'hours'
DAYS = 'days'
MONTHS = 'months'

# available authorization strategy
OAUTH2_AUTH_STRATEGY = 'OAUTH2'
BASIC_AUTH_STRATEGY = 'BASIC'
