query-plan:
  tables:
    partition_column: version
    table_names:
      - finance_l1.dim_banks_staging
  variables:
    TABLES_TO_REWRITE:
      - finance_l1.dim_banks_latest
  queries:
    - description: copy from tmp
      staging-table: finance_l1.dim_banks_staging
      partition-column: version
      sql: |
        INSERT INTO finance_l1.dim_banks_latest
        SELECT
          id,
          name,
          version
        FROM finance_l1.dim_banks_staging
        WHERE {BATCH_HIGH_LOW_FILTER};