query-plan:
  tables:
    partition_column: version
    table_names:
      - hr_l2.dim_hr_tool_leave_reason_staging
  variables:
    TABLES_TO_REWRITE:
      - hr_l2.dim_hr_tool_leave_reason_latest
  queries:
    - description: overwrite latest
      staging-table: hr_l2.dim_hr_tool_leave_reason_staging
      partition-column: version
      sql: |
        INSERT INTO hr_l2.dim_hr_tool_leave_reason_latest (
        	version,
        	id,
        	name,
        	created_at,
        	updated_at,
        	deleted_at
        	)
        SELECT version,
        	id,
        	name,
        	created_at,
        	updated_at,
        	deleted_at
        FROM hr_l2.dim_hr_tool_leave_reason_staging
        WHERE {BATCH_HIGH_LOW_FILTER};