query-plan:
  tables:
    partition_column: version
    table_names:
      - commons_l3.dim_city_staging
  variables:
    TABLES_TO_REWRITE:
      - commons_l3.dim_city_latest
  queries:
    - description: copy from staging table
      staging-table: commons_l3.dim_city_staging
      partition-column: version
      sql: |
        INSERT INTO commons_l3.dim_city_latest
        SELECT
          id,
          name,
          country_id,
          name_eng,
          has_office,
          deletion_mark,
          version
        FROM commons_l3.dim_city_staging
        WHERE {BATCH_HIGH_LOW_FILTER};