query-plan:
  tables:
    partition_column: version
    table_names:
      - commons_l3.dim_categories_history_staging
  variables:
    TABLES_TO_REWRITE:
      - commons_l3.dim_categories_history_latest
  queries:
    - description: copy from tmp
      staging-table: commons_l3.dim_categories_history_staging
      partition-column: version
      sql: |
        WITH distinct_categories_change
        AS (
        	SELECT *,
        		ROW_NUMBER() OVER (
        			PARTITION BY employee_id, category_id, date ORDER BY date ASC
        			) rn
        	FROM commons_l3.dim_categories_history_staging
        	WHERE {BATCH_HIGH_LOW_FILTER}
        	)
        
        INSERT INTO commons_l3.dim_categories_history_latest(
          version,
          date, 
          df, 
          employee_id, 
          category_id
        )
        SELECT version,
        	date,
            CAST(date AS DATE) AS df,
        	employee_id,
        	category_id
        FROM distinct_categories_change
        WHERE rn = 1;