query-plan:
  tables:
    partition_column: version
    table_names:
      - commons_l3.dim_technology_1c_staging
  variables:
    TABLES_TO_REWRITE:
      - commons_l3.dim_technology_1c_latest
  queries:
    - description: copy from tmp
      staging-table: commons_l3.dim_technology_1c_staging
      partition-column: version
      sql: |
        INSERT INTO commons_l3.dim_technology_1c_latest
        SELECT
          id,
          name,
          deletion_mark,
          version
        FROM commons_l3.dim_technology_1c_staging
        WHERE {BATCH_HIGH_LOW_FILTER};