query-plan:
  tables:
    partition_column: version
    table_names:
      - commons_l3.dim_positions_staging
  variables:
    TABLES_TO_REWRITE:
      - commons_l3.dim_positions_latest
  queries:
    - description: copy from tmp
      staging-table: commons_l3.dim_positions_staging
      partition-column: version
      sql: |
        INSERT INTO commons_l3.dim_positions_latest
        SELECT
          version,
          id,
          name,
          seniority,
          seniority_id
        FROM commons_l3.dim_positions_staging
        WHERE {BATCH_HIGH_LOW_FILTER};