query-plan:
  tables:
    partition_column: version
    table_names:
      - commons_l3.dim_organizational_units_staging
  variables:
    TABLES_TO_REWRITE:
      - commons_l3.dim_organizational_units_latest
  queries:
    - description: copy organizational unit from staging
      staging-table: commons_l3.dim_organizational_units_staging
      partition-column: version
      sql: |
         INSERT INTO commons_l3.dim_organizational_units_latest (
            version,
            id,
            parent_unit_id,
            unit_type,
            name,
            manager_id,
            manager_deputy_id,
            business_partner_id
            )
         SELECT
            version,
            id,
            parent_unit_id,
            unit_type,
            name,
            JSON_VALUE(manager, '$.employeeId')  AS manager_id,
            JSON_VALUE(manager, '$.deputyId')  AS manager_deputy_id,
            business_partner_id
         FROM commons_l3.dim_organizational_units_staging
         WHERE {BATCH_HIGH_LOW_FILTER};