query-plan:
  tables:
    partition_column: version
    table_names:
      - commons_l3.dim_ets_projects_staging
  variables:
    TABLES_TO_REWRITE:
      - commons_l3.dim_ets_projects_latest
  queries:
    - description: copy from tmp
      staging-table: commons_l3.dim_ets_projects_staging
      partition-column: version
      sql: |
        INSERT INTO commons_l3.dim_ets_projects_latest (
        	version,
        	description,
        	name,
        	id
        	)
        SELECT version,
        	description,
        	name,
        	id
        FROM commons_l3.dim_ets_projects_staging
        WHERE {BATCH_HIGH_LOW_FILTER};