query-plan:
  tables:
    partition_column: version
    table_names:
      - commons_l3.dim_positions_history_staging
  variables:
    TABLES_TO_REWRITE:
      - commons_l3.dim_positions_history_latest
  queries:
    - description: copy from tmp
      staging-table: commons_l3.dim_positions_history_staging
      partition-column: version
      sql: |
        INSERT INTO commons_l3.dim_positions_history_latest
        SELECT
          version,
          date,
          employee_id,
          position_id
        FROM commons_l3.dim_positions_history_staging
        WHERE {BATCH_HIGH_LOW_FILTER};