query-plan:
  tables:
    partition_column: version
    table_names:
      - commons_l3.dim_riksbank_currency_codes_staging
  variables:
    TABLES_TO_REWRITE:
      - commons_l3.dim_riksbank_currency_codes_latest
  queries:
    - description: from staging
      staging-table: commons_l3.dim_riksbank_currency_codes_staging
      partition-column: version
      sql: |
        INSERT INTO commons_l3.dim_riksbank_currency_codes_latest
        SELECT
          series_id,
          source,
          short_description,
          mid_description,
          long_description,
          group_id,
          observation_max_date,
          observation_min_date,
          series_closed,
          version
        FROM commons_l3.dim_riksbank_currency_codes_staging
        WHERE {BATCH_HIGH_LOW_FILTER};