query-plan:
  tables:
    partition_column: version
    table_names:
      - hr_l2.dim_hr_tool_mentor_staging
  variables:
    TABLES_TO_REWRITE:
      - hr_l2.dim_hr_tool_mentor_latest
  queries:
    - description: overwrite latest
      staging-table: hr_l2.dim_hr_tool_mentor_staging
      partition-column: version
      sql: |
        INSERT INTO hr_l2.dim_hr_tool_mentor_latest (
        	version,
        	staff_member_id,
        	mentor_id
        	)
        SELECT version,
        	staff_member_id,
        	mentor_id
        FROM hr_l2.dim_hr_tool_mentor_staging
        WHERE {BATCH_HIGH_LOW_FILTER};