query-plan:
  tables:
    partition_column: version
    table_names:
      - hr_l2.dim_hr_tool_requirement_staging
  variables:
    TABLES_TO_REWRITE:
      - hr_l2.dim_hr_tool_requirement_latest
  queries:
    - description: overwrite latest
      staging-table: hr_l2.dim_hr_tool_requirement_staging
      partition-column: version
      sql: |
        INSERT INTO hr_l2.dim_hr_tool_requirement_latest (
        	version,
        	id,
        	levelId,
        	requirementId,
        	statement,
        	isMandatory
        	)
        SELECT version,
        	id,
        	levelId,
        	requirementId,
        	statement,
        	isMandatory
        FROM hr_l2.dim_hr_tool_requirement_staging
        WHERE {BATCH_HIGH_LOW_FILTER};