query-plan:
  tables:
    partition_column: version
    table_names:
      - finance_l1.dim_bank_accounts_staging
  variables:
    TABLES_TO_REWRITE:
      - finance_l1.dim_bank_accounts_latest
  queries:
    - description: copy last batch from staging into latest, truncating latest table
      staging-table: finance_l1.dim_bank_accounts_staging
      partition-column: version
      sql: |
        INSERT INTO finance_l1.dim_bank_accounts_latest
        SELECT
          bank_id,
          currency_id,
          id,
          name,
          version,
          ssw_party
        FROM finance_l1.dim_bank_accounts_staging
        WHERE {BATCH_HIGH_LOW_FILTER};