query-plan:
  tables:
    partition_column: version
    table_names:
      - commons_l3.dim_departments_staging
  variables:
    TABLES_TO_REWRITE:
      - commons_l3.dim_departments_latest
  queries:
    - description: copy from tmp
      staging-table: commons_l3.dim_departments_staging
      partition-column: version
      sql: |
        INSERT INTO commons_l3.dim_departments_latest
        SELECT
          version,
          id,
          name,
          responsible_manager_id,
          is_delivery_department
        FROM commons_l3.dim_departments_staging
        WHERE {BATCH_HIGH_LOW_FILTER};

