query-plan:
  tables:
    partition_column: version
    table_names:
      - hr_l2.dim_hr_tool_level_staging
  variables:
    TABLES_TO_REWRITE:
      - hr_l2.dim_hr_tool_level_latest
  queries:
    - description: overwrite latest
      staging-table: hr_l2.dim_hr_tool_level_staging
      partition-column: version
      sql: |
        INSERT INTO hr_l2.dim_hr_tool_level_latest (
        	version,
        	id,
        	skillId,
        	levelId,
        	name,
        	description
        	)
        SELECT version,
        	id,
        	skillId,
        	levelId,
        	name,
        	description
        FROM hr_l2.dim_hr_tool_level_staging
        WHERE {BATCH_HIGH_LOW_FILTER};