query-plan:
  tables:
    partition_column: version
    table_names:
      - commons_l3.fact_employees_change_history_staging
  variables:
    TABLES_TO_REWRITE:
      - commons_l3.fact_employees_change_history
  queries:
    - description: copy from tmp
      staging-table: commons_l3.fact_employees_change_history_staging
      partition-column: version
      sql: |
        INSERT INTO commons_l3.fact_employees_change_history (
        	version,
        	type,
        	STATUS,
        	position_id,
        	is_reduction,
        	is_contractor,
        	id,
        	employee_id,
        	department_id,
        	date,
        	attrition,
            reason_extended_leave_id
        	)
        SELECT version,
        	type,
        	STATUS,
        	position_id,
        	is_reduction,
        	is_contractor,
        	id,
        	employee_id,
        	department_id,
        	date,
        	attrition,
            reason_extended_leave_id
        FROM commons_l3.fact_employees_change_history_staging
        WHERE {BATCH_HIGH_LOW_FILTER};
