query-plan:
  tables:
    partition_column: batch_id
    table_names:
      - finance_l2.fact_debt_adjustment_staging
  queries:
    - description: copy debt adjustment from staging table
      staging-table: finance_l2.fact_debt_adjustment_staging
      partition-column: batch_id
      sql: |
        BEGIN TRANSACTION [tran]
        BEGIN TRY
          DELETE FROM finance_l2.fact_debt_adjustment_latest
          WHERE EOMONTH(date) in 
            (SELECT DISTINCT(EOMONTH(date)) FROM finance_l2.fact_debt_adjustment_staging
             WHERE {BATCH_HIGH_LOW_FILTER})
          INSERT INTO finance_l2.fact_debt_adjustment_latest
          SELECT * FROM finance_l2.fact_debt_adjustment_staging
          WHERE {BATCH_HIGH_LOW_FILTER}
          COMMIT TRANSACTION [tran]
        END TRY
        BEGIN CATCH
          ROLLBACK TRANSACTION [tran]
        END CATCH