query-plan:
  tables:
    partition_column: version
    table_names:
      - commons_l3.fact_employees_transfer_dismissal_staging
  variables:
    TABLES_TO_REWRITE:
      - commons_l3.fact_employees_transfer_dismissal_latest
  queries:
    - description: copy from tmp
      staging-table: commons_l3.fact_employees_transfer_dismissal_staging
      partition-column: version
      sql: |
        INSERT INTO commons_l3.fact_employees_transfer_dismissal_latest (
        	version,
            id,
            type,
            date,
            employee_id,
            position_id,
            department_id,
            status,
            is_dismissal,
            is_contractor,
            attrition,
            is_reduction,
            reason_extended_leave_id
        	)
        SELECT version,
            id,
            type,
            date,
            employee_id,
            position_id,
            department_id,
            status,
            is_dismissal,
            is_contractor,
            attrition,
            is_reduction,
            reason_extended_leave_id
        FROM commons_l3.fact_employees_transfer_dismissal_staging
        WHERE {BATCH_HIGH_LOW_FILTER};
