query-plan:
  tables:
    partition_column: version
    table_names:
      - commons_l3.fact_workplaces_history_staging
  variables:
    TABLES_TO_REWRITE:
      - commons_l3.fact_workplaces_history
  queries:
    - description: copy from staging
      staging-table: commons_l3.fact_workplaces_history_staging
      partition-column: version
      sql: |
        INSERT INTO commons_l3.fact_workplaces_history (
        	version,
        	DATE,
            df,
        	employee_id,
        	room_id,
        	works_remotely
        	)
        SELECT version,
        	DATE,
            CAST(DATE AS DATE) AS df,
        	employee_id,
        	room_id,
        	works_remotely
        FROM commons_l3.fact_workplaces_history_staging
        WHERE {BATCH_HIGH_LOW_FILTER};